version: "3.9"
services:
  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER=admin